let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Flower 1",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower2.jpeg",
    },
    {
      id: "ioytrhndcv",
      name: "Flower 2",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower7.jpeg",
    },
    {
      id: "wuefbncxbsn",
      name: "Flower 3",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower3.jpeg",
    },
    {
      id: "thyfhcbcv",
      name: "Flower 4",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower4.jpeg",
    }, {
      id: "thiecbawdjksadjk",
      name: "Flower 5",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower5.jpeg",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Flower 6",
      price: 200,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower6.jpeg",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "Flower 7",
      price: 450,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower7.jpeg",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "Flower 8",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower8.jpeg",
    },
    {
      id: "cbvxbcvsceldk",
      name: "Flower 9",
      price: 85,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower9.jpeg",
    },
    {
      id: "oiopijmjkhuihb",
      name: "Flower 10",
      price: 120,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower10.jpeg",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "Flower 11",
      price: 35,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower11.jpeg",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Flower 12",
      price: 350,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "/E-commerce-flower-website/images/flower12.jpeg",
    },
  ];
  